# Generated by Django 3.2.4 on 2021-06-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210612_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='telefon',
            new_name='phone',
        ),
    ]
