# Generated by Django 3.2.4 on 2021-06-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_telefon_subscriber_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
