# Generated by Django 3.2.4 on 2021-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
