# Generated by Django 3.2.4 on 2021-07-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210625_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
